# Generated by Django 3.0.7 on 2021-11-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('representative', models.CharField(max_length=100)),
                ('social_security_number', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CO2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('VIN', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.CustomerModel')),
                ('results', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.ResultsModel')),
                ('vehicle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.VehicleModel')),
            ],
        ),
    ]
